### ISSUE TITLE
Do you know anything about driver development?

### ISSUE THREAD

**Issue by Zero3K** [DoaJCBlogger/Talk32#6]
*subject*

**Comment by DoaJCBlogger** [comment]
A little. I started working on a graphics driver for the Intel UHD Graphics 605 for Windows XP x64 but I couldn't find a computer to test it on.

**Comment by Zero3K** [comment]
There's an audio driver that I am wanting added to ReactOS' source code (which is available at https://github.com/reactos/reactos). It works fine for the most part (just need to figure out why its causing AIMP 4 to not play audio files). I made a video of it being used under ReactOS. It can be found at https://www.youtube.com/watch?v=rSdz8YnWDZ0. The patch to get the driver to be added to its source code can be found at https://gist.githubusercontent.com/Zero3K/f021f5446f5dbdc695caebf60f4ad9b3/raw/752f910f793680ed5984ab8bff96ab92706821be/ac97_import_new2.patch

**Comment by DoaJCBlogger** [comment]
I don't know anything about audio drivers so I probably can't help.

**Comment by Zero3K** [comment]
Okay.

**Comment by Zero3K** [comment]
The audio driver has been finished earlier this year and added to ReactOS a while after.

**Comment by K4sum1** [comment]
> The audio driver has been finished earlier this year and added to ReactOS a while after.

I'm curious, is it like a generic driver that could benefit XP users?

**Comment by Zero3K** [comment]
It's for AC'97 based audio cards/chips (like the one emulated by VirtualBox).
